version: '3.8'
services:
  mysql_259:
    env_file:
      - .env
    container_name:  mysql_259
    hostname:  mysql_259
    image: mysql:8
    restart: always
    command:
      - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_259:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo